# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions copyright [year] [name of copyright owner]".
#
# Copyright 2026 OSSTech Corporation
#

# Controls the section ordering of properties in the RestSecurityTokenService

# General Configuration
general=persist-issued-tokens-in-cts
general=supported-token-transforms
general=custom-token-validators
general=custom-token-providers
general=custom-token-transforms

# Deployment Configuration
deployment=deployment-url-element
deployment=deployment-auth-target-mappings
deployment=deployment-offloaded-two-way-tls-header-key
deployment=deployment-tls-offload-engine-hosts

# Issued SAML2 Token Configuration
saml2Token=issuer-name
saml2Token=saml2-sp-entity-id
saml2Token=saml2-sp-acs-url
saml2Token=saml2-name-id-format
saml2Token=saml2-token-lifetime-seconds
saml2Token=saml2-custom-conditions-provider-class-name
saml2Token=saml2-custom-subject-provider-class-name
saml2Token=saml2-custom-authentication-statements-provider-class-name
saml2Token=saml2-custom-attribute-statements-provider-class-name
saml2Token=saml2-custom-authz-decision-statements-provider-class-name
saml2Token=saml2-custom-attribute-mapper-class-name
saml2Token=saml2-custom-authn-context-mapper-class-name
saml2Token=saml2-attribute-map
saml2Token=saml2-sign-assertion
saml2Token=saml2-encrypt-assertion
saml2Token=saml2-encrypt-attributes
saml2Token=saml2-encrypt-nameid
saml2Token=saml2-encryption-algorithm
saml2Token=saml2-keystore-filename
saml2Token=saml2-keystore-password
saml2Token=saml2-encryption-key-alias
saml2Token=saml2-signature-key-alias
saml2Token=saml2-signature-key-password

# OpenIdConnect Token Configuration
oidcToken=oidc-issuer
oidcToken=oidc-token-lifetime-seconds
oidcToken=oidc-signature-algorithm
oidcToken=oidc-public-key-reference-type
oidcToken=oidc-keystore-location
oidcToken=oidc-keystore-password
oidcToken=oidc-signature-key-alias
oidcToken=oidc-signature-key-password
oidcToken=oidc-client-secret
oidcToken=oidc-audience
oidcToken=oidc-authorized-party
oidcToken=oidc-claim-map
oidcToken=oidc-custom-claim-mapper-class
oidcToken=oidc-custom-authn-context-mapper-class
oidcToken=oidc-custom-authn-method-references-mapper-class

