//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:15 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.25 at 07:36:02 AM UTC 
//


package com.sun.identity.saml2.jaxb.metadataui;


/**
 * Java content class for Description element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/oishi/openam-14.0.0-source/openam-14.0.0/openam-schema/openam-saml2-schema/src/main/xsd/sstc-saml-metadata-ui-v1.0.xsd line 55)
 * <p>
 * <pre>
 * &lt;element name="Description" type="{urn:oasis:names:tc:SAML:2.0:metadata}localizedNameType"/>
 * </pre>
 * 
 */
public interface DescriptionElement
    extends javax.xml.bind.Element, com.sun.identity.saml2.jaxb.metadata.LocalizedNameType
{


}
