#
# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions copyright [year] [name of copyright owner]".
#
# Copyright 2026 OSSTech Corporation
#
openam-saml2-metadata-auto-reload-description=SAMLv2 Metadata Auto Reload

a101=Mapping with Metadata URL and Backup Path
a101.help=The url which the metadata is served from and corresponding path of the backup file.
a101.help.txt=The key must be a url and the value must be a path to the backup file.
a102=Execution Time
a102.help=The time in which this task is executed.
a102.help.txt=The task is executed once per day. Specify the time in format of <code>hh:mm:ss</code>.<br/> (e.g. <code>03:00:00</code> ... The task is executed at 3:00 A.M. every day.)
a103=Execution Server URL
a103.help=The url of the server which execute the task.
a103.help.txt=To avoid conflict between multiple update opration, the task must be executed in only one server. Specify a url of the server excute the task. If this server is not configured for multiple instances, this setting is ignored.
a104=Target Role
a104.help=The role of entities being updated.
a105=Include Entities
a105.help=Id of entities being updated.
a105.help.txt=Multiple entities can be specified. Specified entities are updated although "Target Role" setting doesn't match the role.
a106=Exclude Entities
a106.help=Id of entities being not updated
a106.help.txt=Multiple entities can be specified. Specified entities are not updated although "Target Role" setting matches the role.
a107=Check Expiration Date
a107.help=Check expiration date of the metadata and the configuration will not be updated if expired.
a108=Validate Signature
a108.help=Validate signature of the metadata and the configuration will not be updated if invalid.
a109=Allow Create Entities
a109.help=Allow adding new entities to OpenAM when new entities are added in the metadata.

a201=All
a202=SP Only
a203=IdP Only
a204=Nothing

i18nTrue=Enable
i18nFalse=Disable
