//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:15 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.25 at 07:36:02 AM UTC 
//


package com.sun.identity.saml2.jaxb.metadataui.impl;

public class DiscoHintsTypeImpl implements com.sun.identity.saml2.jaxb.metadataui.DiscoHintsType, com.sun.xml.bind.JAXBObject, com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallableObject, com.sun.identity.saml2.jaxb.assertion.impl.runtime.XMLSerializable, com.sun.identity.saml2.jaxb.assertion.impl.runtime.ValidatableObject
{

    protected com.sun.xml.bind.util.ListImpl _IPHintOrDomainHintOrGeolocationHint;
    public final static java.lang.Class version = (com.sun.identity.saml2.jaxb.metadataui.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.sun.identity.saml2.jaxb.metadataui.DiscoHintsType.class);
    }

    protected com.sun.xml.bind.util.ListImpl _getIPHintOrDomainHintOrGeolocationHint() {
        if (_IPHintOrDomainHintOrGeolocationHint == null) {
            _IPHintOrDomainHintOrGeolocationHint = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _IPHintOrDomainHintOrGeolocationHint;
    }

    public java.util.List getIPHintOrDomainHintOrGeolocationHint() {
        return _getIPHintOrDomainHintOrGeolocationHint();
    }

    public com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallingContext context) {
        return new com.sun.identity.saml2.jaxb.metadataui.impl.DiscoHintsTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.sun.identity.saml2.jaxb.assertion.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_IPHintOrDomainHintOrGeolocationHint == null)? 0 :_IPHintOrDomainHintOrGeolocationHint.size());
        while (idx1 != len1) {
            {
                java.lang.Object o = _IPHintOrDomainHintOrGeolocationHint.get(idx1);
                if (o instanceof com.sun.xml.bind.JAXBObject) {
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _IPHintOrDomainHintOrGeolocationHint.get(idx1 ++)), "IPHintOrDomainHintOrGeolocationHint");
                } else {
                    if (o instanceof java.lang.Object) {
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _IPHintOrDomainHintOrGeolocationHint.get(idx1 ++)), "IPHintOrDomainHintOrGeolocationHint");
                    } else {
                        com.sun.identity.saml2.jaxb.assertion.impl.runtime.Util.handleTypeMismatchError(context, this, "IPHintOrDomainHintOrGeolocationHint", o);
                    }
                }
            }
        }
    }

    public void serializeAttributes(com.sun.identity.saml2.jaxb.assertion.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_IPHintOrDomainHintOrGeolocationHint == null)? 0 :_IPHintOrDomainHintOrGeolocationHint.size());
        while (idx1 != len1) {
            {
                java.lang.Object o = _IPHintOrDomainHintOrGeolocationHint.get(idx1);
                if (o instanceof com.sun.xml.bind.JAXBObject) {
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _IPHintOrDomainHintOrGeolocationHint.get(idx1 ++)), "IPHintOrDomainHintOrGeolocationHint");
                } else {
                    if (o instanceof java.lang.Object) {
                        idx1 += 1;
                    } else {
                        com.sun.identity.saml2.jaxb.assertion.impl.runtime.Util.handleTypeMismatchError(context, this, "IPHintOrDomainHintOrGeolocationHint", o);
                    }
                }
            }
        }
    }

    public void serializeURIs(com.sun.identity.saml2.jaxb.assertion.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_IPHintOrDomainHintOrGeolocationHint == null)? 0 :_IPHintOrDomainHintOrGeolocationHint.size());
        while (idx1 != len1) {
            {
                java.lang.Object o = _IPHintOrDomainHintOrGeolocationHint.get(idx1);
                if (o instanceof com.sun.xml.bind.JAXBObject) {
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _IPHintOrDomainHintOrGeolocationHint.get(idx1 ++)), "IPHintOrDomainHintOrGeolocationHint");
                } else {
                    if (o instanceof java.lang.Object) {
                        idx1 += 1;
                    } else {
                        com.sun.identity.saml2.jaxb.assertion.impl.runtime.Util.handleTypeMismatchError(context, this, "IPHintOrDomainHintOrGeolocationHint", o);
                    }
                }
            }
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.sun.identity.saml2.jaxb.metadataui.DiscoHintsType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gramm"
+"ar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expression"
+"\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bex"
+"pandedExpq\u0000~\u0000\u0002xpppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002x"
+"q\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0000q\u0000~\u0000\n"
+"psq\u0000~\u0000\u0000q\u0000~\u0000\npsq\u0000~\u0000\u0000q\u0000~\u0000\npsr\u0000\'com.sun.msv.grammar.trex.Elemen"
+"tPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameC"
+"lass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreU"
+"ndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\np\u0000sq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0006q\u0000~\u0000\npsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L"
+"\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u000fxq\u0000~\u0000\u0003q\u0000~\u0000\npsr\u00002com.sun.msv.gramm"
+"ar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\t\u0001q\u0000~"
+"\u0000\u0017sr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun"
+".msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.E"
+"xpression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u0018q\u0000~\u0000\u001dsr\u0000#co"
+"m.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012L"
+"java/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\u001fxq\u0000~\u0000\u001at\u00004com.sun.identi"
+"ty.saml2.jaxb.metadataui.IPHintElementt\u0000+http://java.sun.com"
+"/jaxb/xjc/dummy-elementssq\u0000~\u0000\u000eq\u0000~\u0000\np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0006q\u0000~\u0000\npsq\u0000"
+"~\u0000\u0014q\u0000~\u0000\npq\u0000~\u0000\u0017q\u0000~\u0000\u001bq\u0000~\u0000\u001dsq\u0000~\u0000\u001et\u00008com.sun.identity.saml2.jaxb"
+".metadataui.DomainHintElementq\u0000~\u0000\"sq\u0000~\u0000\u000eq\u0000~\u0000\np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000"
+"\u0006q\u0000~\u0000\npsq\u0000~\u0000\u0014q\u0000~\u0000\npq\u0000~\u0000\u0017q\u0000~\u0000\u001bq\u0000~\u0000\u001dsq\u0000~\u0000\u001et\u0000=com.sun.identity."
+"saml2.jaxb.metadataui.GeolocationHintElementq\u0000~\u0000\"sq\u0000~\u0000\u000eq\u0000~\u0000\n"
+"p\u0000sq\u0000~\u0000\u0014ppq\u0000~\u0000\u0017sr\u0000\'com.sun.msv.grammar.DifferenceNameClass\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003nc1q\u0000~\u0000\u000fL\u0000\u0003nc2q\u0000~\u0000\u000fxq\u0000~\u0000\u001aq\u0000~\u0000\u001bsr\u0000#com.sun.msv.gr"
+"ammar.ChoiceNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003nc1q\u0000~\u0000\u000fL\u0000\u0003nc2q\u0000~\u0000\u000fxq\u0000~\u0000\u001a"
+"sr\u0000&com.sun.msv.grammar.NamespaceNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\fname"
+"spaceURIq\u0000~\u0000\u001fxq\u0000~\u0000\u001at\u0000\u0000sq\u0000~\u00005t\u0000#urn:oasis:names:tc:SAML:metad"
+"ata:uisq\u0000~\u00005q\u0000~\u0000\"q\u0000~\u0000\u001dsr\u0000\"com.sun.msv.grammar.ExpressionPool"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool"
+"$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedH"
+"ash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/m"
+"sv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u000b\u0001pq\u0000~\u0000\rq\u0000~\u0000\u0005q\u0000~\u0000\u000bq\u0000~\u0000\fq\u0000~\u0000\u0013q"
+"\u0000~\u0000%q\u0000~\u0000+q\u0000~\u0000\u0012q\u0000~\u0000$q\u0000~\u0000*q\u0000~\u0000\bx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.sun.identity.saml2.jaxb.assertion.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallingContext context) {
            super(context, "--");
        }

        protected Unmarshaller(com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.sun.identity.saml2.jaxb.metadataui.impl.DiscoHintsTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        if (("IPHint" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getIPHintOrDomainHintOrGeolocationHint().add(((com.sun.identity.saml2.jaxb.metadataui.impl.IPHintElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.IPHintElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("DomainHint" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getIPHintOrDomainHintOrGeolocationHint().add(((com.sun.identity.saml2.jaxb.metadataui.impl.DomainHintElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.DomainHintElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("GeolocationHint" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getIPHintOrDomainHintOrGeolocationHint().add(((com.sun.identity.saml2.jaxb.metadataui.impl.GeolocationHintElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.GeolocationHintElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (!(("" == ___uri)||("urn:oasis:names:tc:SAML:metadata:ui" == ___uri))) {
                            java.lang.Object co = spawnWildcard(1, ___uri, ___local, ___qname, __atts);
                            if (co!= null) {
                                _getIPHintOrDomainHintOrGeolocationHint().add(co);
                            }
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("IPHint" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getIPHintOrDomainHintOrGeolocationHint().add(((com.sun.identity.saml2.jaxb.metadataui.impl.IPHintElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.IPHintElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("DomainHint" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getIPHintOrDomainHintOrGeolocationHint().add(((com.sun.identity.saml2.jaxb.metadataui.impl.DomainHintElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.DomainHintElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("GeolocationHint" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getIPHintOrDomainHintOrGeolocationHint().add(((com.sun.identity.saml2.jaxb.metadataui.impl.GeolocationHintElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.GeolocationHintElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (!(("" == ___uri)||("urn:oasis:names:tc:SAML:metadata:ui" == ___uri))) {
                            java.lang.Object co = spawnWildcard(1, ___uri, ___local, ___qname, __atts);
                            if (co!= null) {
                                _getIPHintOrDomainHintOrGeolocationHint().add(co);
                            }
                            return ;
                        }
                        state = 1;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        state = 1;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        state = 1;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        state = 1;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            revertToParentFromText(value);
                            return ;
                        case  0 :
                            state = 1;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
