//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:15 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.25 at 07:36:02 AM UTC 
//


package com.sun.identity.saml2.jaxb.metadataui.impl;

public class JAXBVersion {

    public final static java.lang.String version = "1.0.6";

}
