//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:15 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.25 at 07:36:02 AM UTC 
//


package com.sun.identity.saml2.jaxb.metadataui.impl;

public class UIInfoTypeImpl implements com.sun.identity.saml2.jaxb.metadataui.UIInfoType, com.sun.xml.bind.JAXBObject, com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallableObject, com.sun.identity.saml2.jaxb.assertion.impl.runtime.XMLSerializable, com.sun.identity.saml2.jaxb.assertion.impl.runtime.ValidatableObject
{

    protected com.sun.xml.bind.util.ListImpl _DisplayNameOrDescriptionOrKeywords;
    public final static java.lang.Class version = (com.sun.identity.saml2.jaxb.metadataui.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.sun.identity.saml2.jaxb.metadataui.UIInfoType.class);
    }

    protected com.sun.xml.bind.util.ListImpl _getDisplayNameOrDescriptionOrKeywords() {
        if (_DisplayNameOrDescriptionOrKeywords == null) {
            _DisplayNameOrDescriptionOrKeywords = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _DisplayNameOrDescriptionOrKeywords;
    }

    public java.util.List getDisplayNameOrDescriptionOrKeywords() {
        return _getDisplayNameOrDescriptionOrKeywords();
    }

    public com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallingContext context) {
        return new com.sun.identity.saml2.jaxb.metadataui.impl.UIInfoTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.sun.identity.saml2.jaxb.assertion.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_DisplayNameOrDescriptionOrKeywords == null)? 0 :_DisplayNameOrDescriptionOrKeywords.size());
        while (idx1 != len1) {
            {
                java.lang.Object o = _DisplayNameOrDescriptionOrKeywords.get(idx1);
                if (o instanceof com.sun.xml.bind.JAXBObject) {
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _DisplayNameOrDescriptionOrKeywords.get(idx1 ++)), "DisplayNameOrDescriptionOrKeywords");
                } else {
                    if (o instanceof java.lang.Object) {
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _DisplayNameOrDescriptionOrKeywords.get(idx1 ++)), "DisplayNameOrDescriptionOrKeywords");
                    } else {
                        com.sun.identity.saml2.jaxb.assertion.impl.runtime.Util.handleTypeMismatchError(context, this, "DisplayNameOrDescriptionOrKeywords", o);
                    }
                }
            }
        }
    }

    public void serializeAttributes(com.sun.identity.saml2.jaxb.assertion.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_DisplayNameOrDescriptionOrKeywords == null)? 0 :_DisplayNameOrDescriptionOrKeywords.size());
        while (idx1 != len1) {
            {
                java.lang.Object o = _DisplayNameOrDescriptionOrKeywords.get(idx1);
                if (o instanceof com.sun.xml.bind.JAXBObject) {
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _DisplayNameOrDescriptionOrKeywords.get(idx1 ++)), "DisplayNameOrDescriptionOrKeywords");
                } else {
                    if (o instanceof java.lang.Object) {
                        idx1 += 1;
                    } else {
                        com.sun.identity.saml2.jaxb.assertion.impl.runtime.Util.handleTypeMismatchError(context, this, "DisplayNameOrDescriptionOrKeywords", o);
                    }
                }
            }
        }
    }

    public void serializeURIs(com.sun.identity.saml2.jaxb.assertion.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_DisplayNameOrDescriptionOrKeywords == null)? 0 :_DisplayNameOrDescriptionOrKeywords.size());
        while (idx1 != len1) {
            {
                java.lang.Object o = _DisplayNameOrDescriptionOrKeywords.get(idx1);
                if (o instanceof com.sun.xml.bind.JAXBObject) {
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _DisplayNameOrDescriptionOrKeywords.get(idx1 ++)), "DisplayNameOrDescriptionOrKeywords");
                } else {
                    if (o instanceof java.lang.Object) {
                        idx1 += 1;
                    } else {
                        com.sun.identity.saml2.jaxb.assertion.impl.runtime.Util.handleTypeMismatchError(context, this, "DisplayNameOrDescriptionOrKeywords", o);
                    }
                }
            }
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.sun.identity.saml2.jaxb.metadataui.UIInfoType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gramm"
+"ar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expression"
+"\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bex"
+"pandedExpq\u0000~\u0000\u0002xpppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002x"
+"q\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0000q\u0000~\u0000\n"
+"psq\u0000~\u0000\u0000q\u0000~\u0000\npsq\u0000~\u0000\u0000q\u0000~\u0000\npsq\u0000~\u0000\u0000q\u0000~\u0000\npsq\u0000~\u0000\u0000q\u0000~\u0000\npsq\u0000~\u0000\u0000q\u0000~\u0000\n"
+"psr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tna"
+"meClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.gra"
+"mmar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fco"
+"ntentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0006q\u0000~\u0000\npsr\u0000 com.sun."
+"msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000"
+"~\u0000\u0012xq\u0000~\u0000\u0003q\u0000~\u0000\npsr\u00002com.sun.msv.grammar.Expression$AnyStringE"
+"xpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\t\u0001q\u0000~\u0000\u001asr\u0000 com.sun.msv.gramma"
+"r.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$EpsilonExpress"
+"ion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u001bq\u0000~\u0000 sr\u0000#com.sun.msv.grammar.Simple"
+"NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fname"
+"spaceURIq\u0000~\u0000\"xq\u0000~\u0000\u001dt\u00009com.sun.identity.saml2.jaxb.metadataui"
+".DisplayNameElementt\u0000+http://java.sun.com/jaxb/xjc/dummy-ele"
+"mentssq\u0000~\u0000\u0011q\u0000~\u0000\np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0006q\u0000~\u0000\npsq\u0000~\u0000\u0017q\u0000~\u0000\npq\u0000~\u0000\u001aq\u0000~\u0000\u001e"
+"q\u0000~\u0000 sq\u0000~\u0000!t\u00009com.sun.identity.saml2.jaxb.metadataui.Descrip"
+"tionElementq\u0000~\u0000%sq\u0000~\u0000\u0011q\u0000~\u0000\np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0006q\u0000~\u0000\npsq\u0000~\u0000\u0017q\u0000~\u0000\n"
+"pq\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!t\u00006com.sun.identity.saml2.jaxb.metadat"
+"aui.KeywordsElementq\u0000~\u0000%sq\u0000~\u0000\u0011q\u0000~\u0000\np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0006q\u0000~\u0000\npsq\u0000"
+"~\u0000\u0017q\u0000~\u0000\npq\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!t\u00002com.sun.identity.saml2.jaxb"
+".metadataui.LogoElementq\u0000~\u0000%sq\u0000~\u0000\u0011q\u0000~\u0000\np\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0006q\u0000~\u0000\n"
+"psq\u0000~\u0000\u0017q\u0000~\u0000\npq\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!t\u0000<com.sun.identity.saml2."
+"jaxb.metadataui.InformationURLElementq\u0000~\u0000%sq\u0000~\u0000\u0011q\u0000~\u0000\np\u0000sq\u0000~\u0000"
+"\u0000ppsq\u0000~\u0000\u0006q\u0000~\u0000\npsq\u0000~\u0000\u0017q\u0000~\u0000\npq\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!t\u0000Acom.sun.i"
+"dentity.saml2.jaxb.metadataui.PrivacyStatementURLElementq\u0000~\u0000"
+"%sq\u0000~\u0000\u0011q\u0000~\u0000\np\u0000sq\u0000~\u0000\u0017ppq\u0000~\u0000\u001asr\u0000\'com.sun.msv.grammar.Differenc"
+"eNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003nc1q\u0000~\u0000\u0012L\u0000\u0003nc2q\u0000~\u0000\u0012xq\u0000~\u0000\u001dq\u0000~\u0000\u001esr\u0000#co"
+"m.sun.msv.grammar.ChoiceNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003nc1q\u0000~\u0000\u0012L\u0000\u0003nc"
+"2q\u0000~\u0000\u0012xq\u0000~\u0000\u001dsr\u0000&com.sun.msv.grammar.NamespaceNameClass\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0001L\u0000\fnamespaceURIq\u0000~\u0000\"xq\u0000~\u0000\u001dt\u0000\u0000sq\u0000~\u0000Jt\u0000#urn:oasis:names:t"
+"c:SAML:metadata:uisq\u0000~\u0000Jq\u0000~\u0000%q\u0000~\u0000 sr\u0000\"com.sun.msv.grammar.Ex"
+"pressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Ex"
+"pressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Expression"
+"Pool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt"
+"\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u0014\u0001pq\u0000~\u0000\fq\u0000~\u0000\u0010q\u0000~\u0000"
+"\rq\u0000~\u0000\u000bq\u0000~\u0000\u000eq\u0000~\u0000\u000fq\u0000~\u0000\u0005q\u0000~\u0000\u0016q\u0000~\u0000(q\u0000~\u0000.q\u0000~\u00004q\u0000~\u0000\u0015q\u0000~\u0000\'q\u0000~\u0000-q\u0000~\u0000"
+"3q\u0000~\u0000:q\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000?q\u0000~\u0000\bx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.sun.identity.saml2.jaxb.assertion.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallingContext context) {
            super(context, "--");
        }

        protected Unmarshaller(com.sun.identity.saml2.jaxb.assertion.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.sun.identity.saml2.jaxb.metadataui.impl.UIInfoTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        if (("DisplayName" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.DisplayNameElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.DisplayNameElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Description" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.DescriptionElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.DescriptionElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Keywords" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.KeywordsElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.KeywordsElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Logo" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.LogoElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.LogoElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("InformationURL" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.InformationURLElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.InformationURLElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("PrivacyStatementURL" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.PrivacyStatementURLElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.PrivacyStatementURLElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (!(("" == ___uri)||("urn:oasis:names:tc:SAML:metadata:ui" == ___uri))) {
                            java.lang.Object co = spawnWildcard(1, ___uri, ___local, ___qname, __atts);
                            if (co!= null) {
                                _getDisplayNameOrDescriptionOrKeywords().add(co);
                            }
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("DisplayName" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.DisplayNameElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.DisplayNameElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Description" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.DescriptionElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.DescriptionElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Keywords" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.KeywordsElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.KeywordsElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Logo" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.LogoElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.LogoElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("InformationURL" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.InformationURLElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.InformationURLElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("PrivacyStatementURL" == ___local)&&("urn:oasis:names:tc:SAML:metadata:ui" == ___uri)) {
                            _getDisplayNameOrDescriptionOrKeywords().add(((com.sun.identity.saml2.jaxb.metadataui.impl.PrivacyStatementURLElementImpl) spawnChildFromEnterElement((com.sun.identity.saml2.jaxb.metadataui.impl.PrivacyStatementURLElementImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (!(("" == ___uri)||("urn:oasis:names:tc:SAML:metadata:ui" == ___uri))) {
                            java.lang.Object co = spawnWildcard(1, ___uri, ___local, ___qname, __atts);
                            if (co!= null) {
                                _getDisplayNameOrDescriptionOrKeywords().add(co);
                            }
                            return ;
                        }
                        state = 1;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        state = 1;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        state = 1;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        state = 1;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            revertToParentFromText(value);
                            return ;
                        case  0 :
                            state = 1;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
