#
# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions copyright [year] [name of copyright owner]".
#
# Portions Copyright 2026 OSSTech Corporation
#

authchainswitch-service-description=AuthChain Switch Authentication Module
a500=Authentication Level
a500.help=The authentication level associated with this module.
a501=Attribute Name
a501.help=Use the attribute value of the user to determine the authentication chain.
a502=Default Auth Chain
a502.help=Authenticate with this auth chain when no user attributes exist.
a502.help.txt=If <code>[Empty]</code> is set as the authentication chain, authentication will be successful without calling the authentication chain.
a503=Attribute Value Map ServiceName
a503.help=Set <code>Attribute value</code> to <code>Key</code> and <code>Authentication chain</code> to <code>Value</code>.
a503.help.txt=If <code>[Empty]</code> is set as the authentication chain, authentication will be successful without calling the authentication chain.
a504=Successful authentication with [Empty] during session upgrade
a504.help=This setting is used only during session upgrade.
a504.help.txt=<code>Enable</code>, <code>[Empty]</code> can be used during session upgrade. <br> \
<code>Disabled</code>, <code>[Empty]</code> can't be used during session upgrade. If <code>[Empty]</code> runs, an authentication error will occur.
a505=Cookie Name
a505.help=Use as the name of the cookie that stores the authentication chain.
a505.help.txt=The saved cookie will be used to select the previously selected authentication method by default the next time the selection screen is displayed.
a506=Cookie Expires
a506.help=Set the expiration date of the cookie to be saved.
a506.help.txt=The unit is days. If <code>0</code> is set, no cookie is issued.
a507=Authentication Error for Users with Attributes Not Included in the "Attribute Value Map ServiceName"
a507.help=Set the behavior when even one value not defined in the <code>Attribute Value Map ServiceName</code> is present in the user's attribute values.
a507.help.txt=If this check is enabled; undefined value exists, an authentication error will occur.<br> \
If this check is disabled; undefined value exists, it is ignored and processing continues.

choiceprompt=Please select an authentication method
OK=No additional authentication
HOTP=Notify one-time password to email address
DATASTORE=ID/Password
LDAP=ID/Password
OATH=OATH（Initiative for Open Authentication）

NullRequest=Unable to login without http request.  Programmatic login is not supported.
localAuthChainError=Unable to find service name.
invalidLoginState=Unexpected Error during CheckSession Login.
localAuthFailed=Failed local authentication.  Please try again.
SettingError=The setting value is invalid. Please contact the system administrator
authFailed=Authentication Failed.
sessionUpgradeError=Authentication Failed. Requires additional authentication.
